Repository wallstation13/wallstation13, pull requests merged in 2024-08, with the labels that each got.

#11 Update __odlint.dm
  __odlint.dm
Labels: bugfix, administration, server, config edit, refactor, code improvement, grammer, image, sound, balance, quality of life, removal, feature

#20 [MIRROR] SFX for RCD, RPD, Plumbing constructor
  code/__DEFINES/sound.dm
  code/game/objects/items/rcd/RCD.dm
  code/game/objects/items/rcd/RPD.dm
  code/game/objects/items/rcd/RPLD.dm
  code/game/sound.dm
  sound/items/handling/attribution.txt
  sound/items/handling/rcd_drop.ogg
  sound/items/handling/rcd_pickup.ogg
  sound/items/handling/rpd_drop.ogg
  sound/items/handling/rpd_pickup.ogg
  sound/items/handling/tool_switch.ogg
Labels: sound

#18 [MIRROR] No longer hear radio sounds if you're deaf.
  code/game/objects/items/devices/radio/radio.dm
Labels: bugfix

#16 [MIRROR] Digitigrade clothing sprites (feat. GAGS and 0 sprite bloat)
  code/__DEFINES/inventory.dm
  code/_globalvars/bitfields.dm
  code/datums/greyscale/config_types/greyscale_configs/greyscale_clothes.dm
  code/datums/greyscale/json_configs/jumpsuit_worn_digilegs.json
  code/game/objects/items.dm
  code/game/objects/structures/mannequin.dm
  code/modules/clothing/under/_under.dm
  code/modules/clothing/under/color.dm
  code/modules/clothing/under/jobs/civilian/clown_mime.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/mob/living/carbon/human/_species.dm
  code/modules/mob/living/carbon/human/human_update_icons.dm
  code/modules/surgery/bodyparts/species_parts/lizard_bodyparts.dm
  icons/mob/clothing/under/digi_template.dmi
  icons/mob/clothing/under/masking_helpers.dmi
Labels: feature

#25 [MIRROR] Fixes welding and coil logic on robotic limb fixing
  code/game/objects/items/tools/weldingtool.dm
  code/modules/power/cable.dm
Labels: bugfix

#26 [MIRROR] Makes the Voidwalker wisp void loop
  code/modules/antagonists/voidwalker/voidwalker_kidnap.dm
Labels: quality of life

#27 [MIRROR] Adds a treasure chest to the ocean/beach fishing spot.
  _maps/RandomZLevels/TheBeach.dmm
  code/__DEFINES/language.dm
  code/game/area/areas/away_content.dm
  code/game/objects/effects/spawners/random/exotic.dm
  code/game/objects/effects/spawners/random/food_or_drink.dm
  code/game/objects/items/circuitboards/machines/machine_circuitboards.dm
  code/game/objects/items/food/bait.dm
  code/game/objects/items/weaponry.dm
  code/game/objects/structures/cannons/cannon.dm
  code/game/objects/structures/mystery_box.dm
  code/modules/awaymissions/mission_code/Beach.dm
  code/modules/fishing/aquarium/aquarium_kit.dm
  code/modules/fishing/bait.dm
  code/modules/fishing/fish/_fish.dm
  code/modules/fishing/fishing_equipment.dm
  code/modules/fishing/fishing_portal_machine.dm
  code/modules/fishing/sources/source_types.dm
  code/modules/language/_language_manuals.dm
  code/modules/mob_spawn/corpses/mob_corpses.dm
  code/modules/reagents/chemistry/reagents/drinks/alcohol_reagents.dm
  code/modules/reagents/reagent_containers/cups/bottle.dm
  code/modules/reagents/reagent_containers/cups/glassbottle.dm
  icons/obj/drinks/bottles.dmi
  icons/obj/fishing.dmi
  icons/obj/service/library.dmi
  icons/obj/storage/box.dmi
  icons/obj/storage/crates.dmi
  icons/obj/weapons/cannons.dmi
  tgstation.dme
Labels: feature

#32 [MIRROR] You can sell stuff on the blackmarket now.
  code/__DEFINES/market.dm
  code/game/objects/effects/anomalies/anomalies_bluespace.dm
  code/game/objects/items/devices/swapper.dm
  code/modules/cargo/markets/market_item.dm
  code/modules/cargo/markets/market_items/local_goods.dm
  code/modules/cargo/markets/market_telepad.dm
  code/modules/cargo/markets/market_uplink.dm
  icons/obj/machines/ltsrbt.dmi
  icons/obj/machines/telecomms.dmi
  tgstation.dme
  tgui/packages/tgui/interfaces/BlackMarketUplink.tsx
  tgui/packages/tgui/interfaces/LTSRBT.tsx
Labels: bugfix, feature

#35 [MIRROR] Dumping things into microwave en-masse is done via RMB or drag'n'drop
  code/modules/food_and_drinks/machinery/microwave.dm
Labels: bugfix, quality of life

#34 [MIRROR] Adds a light switch to the science hallway in metastation
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: bugfix

#47 [MIRROR] Drunken Brawlening: Intoxication alters your unarmed effectiveness, bartenders are stronger fighters while drunk, deterministic stagger combo is back (your average assistant doesn't get knockdowns)
  code/__DEFINES/traits/declarations.dm
  code/_globalvars/traits/_traits.dm
  code/modules/jobs/job_types/bartender.dm
  code/modules/library/skill_learning/skillchip.dm
  code/modules/mob/living/carbon/human/_species.dm
  code/modules/mob/living/living.dm
Labels: quality of life, feature

#52 [MIRROR] Adds rolling average usage tracking to SS overview
  code/controllers/master.dm
  code/controllers/subsystem.dm
  tgui/packages/tgui/interfaces/ControllerOverview/OverviewSection.tsx
  tgui/packages/tgui/interfaces/ControllerOverview/SubsystemDialog.tsx
  tgui/packages/tgui/interfaces/ControllerOverview/SubsystemRow.tsx
  tgui/packages/tgui/interfaces/ControllerOverview/contants.ts
  tgui/packages/tgui/interfaces/ControllerOverview/types.ts
Labels: administration

#57 [MIRROR] Resprites Mech Mining Tools
  icons/obj/devices/mecha_equipment.dmi
Labels: image

#59 [MIRROR] Alien beds no longer pretend they can be deconstructed with a wrench
  code/game/objects/structures/beds_chairs/alien_nest.dm
  code/game/objects/structures/beds_chairs/bed.dm
Labels: bugfix

#53 [MIRROR] Adds attack_dir to multiple common damage sources, fixes mechs' directional armor
  code/_onclick/item_attack.dm
  code/game/objects/obj_defense.dm
  code/game/objects/objs.dm
  code/modules/unit_tests/mecha_damage.dm
  code/modules/vehicles/mecha/mecha_defense.dm
Labels: bugfix

#55 [MIRROR] Fixed random lipstick texture, fake syndie lipstick no longer can randomly spawn
  code/game/objects/items/cosmetics.dm
Labels: bugfix

#12 adds rat reagent
  tgstation.dme
  wallstation_modules/rat-reagent.dm
Labels: Feature

#66 [MIRROR] Aliens and digitigrade legs use claw footprint sprite
  code/modules/mob/living/carbon/alien/alien.dm
  code/modules/surgery/bodyparts/species_parts/lizard_bodyparts.dm
Labels: Quality of life

#70 [MIRROR] portable gravity machine
  code/__DEFINES/icon_smoothing.dm
  code/datums/proximity_monitor/fields/gravity.dm
  code/game/machinery/portagrav.dm
  code/game/objects/effects/particles/gravity.dm
  code/game/objects/items/circuitboards/machines/machine_circuitboards.dm
  code/modules/cargo/packs/engineering.dm
  icons/obj/machines/gravity_generator.dmi
  icons/obj/smooth_structures/grav_field.dmi
  icons/obj/smooth_structures/grav_field.png
  icons/obj/smooth_structures/grav_field.png.toml
  icons/obj/smooth_structures/grav_field_emissive.dmi
  icons/obj/smooth_structures/grav_field_emissive.png
  icons/obj/smooth_structures/grav_field_emissive.png.toml
  tgstation.dme
  tgui/packages/tgui/interfaces/Portagrav.tsx
Labels: Feature

#28 [SEMI-MODULAR] Ports Flavor Text from Nova sector, with my adapations from TaleStation
  code/__DEFINES/say.dm
  code/modules/client/preferences/_preference.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/silicon/robot/examine.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/ExaminePanel.jsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/base.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/_multiline_text.tsx
  wallstation_modules/flavor_text_module/examine_tgui.dm
  wallstation_modules/flavor_text_module/preferences_savefile.dm
Labels: Feature

#77 [MIRROR] Fix exploit to get almost-infinite heretic points
  code/modules/antagonists/heretic/knowledge/starting_lore.dm
Labels: bugfix

#87 [MIRROR] Random spraypaint setting now properly paints large decals
  code/game/objects/items/crayons.dm
Labels: bugfix

#84 [MIRROR] Stat change is now logged for living mobs
  code/modules/mob/living/living.dm
Labels: Administration

#80 [MIRROR] Fixes lobby buttons from station traits having no name and being unexaminable.
  code/datums/station_traits/_station_trait.dm
Labels: bugfix

#31 [MIRROR] Changes wall leaning into a component, makes windows leanable
  code/__DEFINES/dcs/signals/signals_mob/signals_mob_living.dm
  code/datums/components/leanable.dm
  code/game/objects/structures/window.dm
  code/game/turfs/closed/walls.dm
  tgstation.dme
Labels: Fix, Feature

#74 [MIRROR] fixes ai controllers incorrectly idling when changing z level
  code/datums/ai/_ai_controller.dm
Labels: bugfix

#94 [MIRROR] Removes the slowdown from the CentCom officer's beret
  code/modules/clothing/spacesuits/specialops.dm
Labels: Quality of life

#96 [MIRROR] Updates worn tank sprites
  icons/mob/clothing/back.dmi
Labels: Image

#97 [MIRROR] Refactored the fish case and examining fish. New bluespace fish case to fit large fish inside a backpack.
  code/__DEFINES/traits/declarations.dm
  code/_globalvars/traits/_traits.dm
  code/_globalvars/traits/admin_tooling.dm
  code/datums/elements/fish_safe_storage.dm
  code/datums/skills/fishing.dm
  code/datums/storage/subtypes/fish_case.dm
  code/game/objects/structures/maintenance.dm
  code/game/objects/structures/water_structures/toilet.dm
  code/modules/fishing/aquarium/aquarium_kit.dm
  code/modules/fishing/fish/_fish.dm
  code/modules/library/skill_learning/skillchip.dm
  code/modules/research/designs/misc_designs.dm
  code/modules/research/techweb/nodes/service_nodes.dm
  icons/obj/storage/case.dmi
  tgstation.dme
Labels: Balance, Feature

#98 [MIRROR] Adds drawing chalk outlines on dead mobs, white crayons are now called sticks of chalk
  code/__DEFINES/living.dm
  code/game/objects/effects/decals/crayon.dm
  code/game/objects/items/crayons.dm
  code/modules/antagonists/heretic/knowledge/lock_lore.dm
  code/modules/cargo/packs/costumes_toys.dm
  code/modules/cargo/packs/security.dm
Labels: Feature

#99 [MIRROR] Fixes Clarke ore box breaking upon collecting boulders
  code/modules/mining/boulder_processing/boulder.dm
  code/modules/vehicles/mecha/working/clarke.dm
Labels: bugfix

#56 Adds blahaj to the loadout
  tgstation.dme
  wallstation_modules/extra_loadout/code/pocket.dm
Labels: Feature

#102 [MIRROR] Fixes heretic summon rituals not consuming items
  code/modules/antagonists/heretic/heretic_knowledge.dm
  code/modules/antagonists/heretic/knowledge/side_ash_moon.dm
  code/modules/antagonists/heretic/knowledge/side_rust_cosmos.dm
Labels: bugfix

#110 [MIRROR] wheelchair + ridden mobs buff
  code/datums/components/riding/riding.dm
  code/datums/components/riding/riding_mob.dm
  code/datums/components/riding/riding_vehicle.dm
Labels: Balance

#117 [MIRROR] Vomiting from disgust now removes 50 disgust from you
  code/modules/surgery/organs/internal/stomach/_stomach.dm
Labels: Balance

#114 [MIRROR] Fixes soapbox component sometimes runtiming roundstart due to not unregistering signals
  code/datums/components/soapbox.dm
Labels: bugfix

#104 [MIRROR] Migrates Issue Reporting to the New GitHub Template Format
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report_form.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  interface/interface.dm
Labels: Quality of life

#127 [MIRROR] Doubles PACMAN power output, triples their sheet efficiency. Inducers can now be recharged with plasma.
  code/game/objects/items/inducer.dm
  code/modules/power/cell.dm
  code/modules/power/port_gen.dm
Labels: Balance

#123 [MIRROR] fixes elevation being permanent if you spawn on it
  code/datums/elements/elevation.dm
Labels: bugfix

#107 [MIRROR] Porting and adapting food sprites from other repos (plus a couple original resprites)
  _maps/RandomRuins/IceRuins/icemoon_surface_pizza.dmm
  _maps/RandomRuins/SpaceRuins/garbagetruck1.dmm
  _maps/RandomZLevels/snowdin.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/wawastation/wawastation.dmm
  code/game/machinery/dish_drive.dm
  code/game/objects/effects/spawners/random/trash.dm
  code/game/objects/items/food/meatslab.dm
  code/game/objects/items/food/pastries.dm
  code/game/objects/items/trash.dm
  icons/obj/food/food.dmi
  icons/obj/food/meat.dmi
  icons/obj/food/mexican.dmi
  tools/UpdatePaths/Scripts/85759_waffle_trash_begone.txt
Labels: Image, Removal

#120 Fixes caves.dmm
  _maps/RandomZLevels/caves.dmm
Labels: bugfix

#128 [MIRROR] Resprites utility belt tool overlays, fixes up grammar for CE's belt
  code/game/objects/items/storage/belt.dm
  icons/obj/clothing/belt_overlays.dmi
Labels: Grammer, Image

#118 (MIRROR) THE WIRING (add wire information for pretty much everything, for the appropriate roles)
  code/__HELPERS/mobs.dm
  code/datums/wires/_wires.dm
  code/datums/wires/apc.dm
  code/datums/wires/collar_bomb.dm
  code/datums/wires/explosive.dm
  code/datums/wires/mecha.dm
  code/datums/wires/mod.dm
  code/datums/wires/robot.dm
  code/datums/wires/syndicatebomb.dm
Labels: Code improvement, Quality of life, Feature

#71 [modular] Removes FOV from atmos gas mask and captain gas mask
  wallstation_modules/gas-mask-fov-override/code/gas-mask-fov-override.dm
Labels: Balance

#86 Passion project again outpost 45update
  _maps/RandomZLevels/undergroundoutpost45.dmm
Labels: Feature

#91 DISABLERING: Disabler Rifle + Disabler SMG Undebarrel Launcher
  tgstation.dme
  wallstation_modules/disablering/code/crafting/guncrafting.dm
  wallstation_modules/disablering/code/crafting/ranged_weapon.dm
  wallstation_modules/disablering/code/projectiles/ammunition/stun.dm
  wallstation_modules/disablering/code/projectiles/guns/grenade_launcher.dm
  wallstation_modules/disablering/code/projectiles/guns/stun.dm
  wallstation_modules/disablering/code/projectiles/projectiles/beams.dm
  wallstation_modules/disablering/code/research/designs/weapon_designs.dm
  wallstation_modules/disablering/code/research/techweb/security_nodes.dm
  wallstation_modules/disablering/icons/back.dmi
  wallstation_modules/disablering/icons/energy.dmi
  wallstation_modules/disablering/icons/guns_lefthand.dmi
  wallstation_modules/disablering/icons/guns_righthand.dmi
  wallstation_modules/disablering/icons/wide_guns.dmi
  wallstation_modules/disablering/sounds/taser_sniper.ogg
Labels: Feature

#138 [MIRROR] Resprites and changes how haunted 8ball polls ghosts
  code/game/objects/items/eightball.dm
Labels: Image, Quality of life

#139 [MIRROR] Cooldown for radio "message received" sound effects
  code/game/objects/items/devices/radio/radio.dm
Labels: Sound

#106 [MIRROR] paintings now drop canvas and frame when knocked off the wall
  code/modules/art/paintings.dm
  icons/obj/art/painting_frames.dmi
Labels: bugfix

#145 [MIRROR] Engineers can now use Air Alarms 3: A New Headcoder
  code/modules/atmospherics/machinery/air_alarm/_air_alarm.dm
Labels: Balance

#148 [MIRROR] Computer console sounds
  code/__DEFINES/sound.dm
  code/game/machinery/computer/_computer.dm
  code/game/machinery/computer/camera.dm
  code/game/machinery/computer/communications.dm
  code/game/machinery/computer/records/records.dm
  code/game/sound.dm
  code/modules/modular_computers/computers/item/computer.dm
  code/modules/wiremod/shell/controller.dm
  sound/machines/computer/attribution.txt
  sound/machines/computer/keyboard_clicks_1.ogg
  sound/machines/computer/keyboard_clicks_2.ogg
  sound/machines/computer/keyboard_clicks_3.ogg
  sound/machines/computer/keyboard_clicks_4.ogg
  sound/machines/computer/keyboard_clicks_5.ogg
  sound/machines/computer/keyboard_clicks_6.ogg
  sound/machines/computer/keyboard_clicks_7.ogg
Labels: Sound

#142 [MIRROR] Replaces a locked cabinet that you cannot open in ninja den with an unlocked one
  _maps/templates/lazy_templates/ninja_den.dmm
Labels: bugfix

#150 [MIRROR] Beepsky no longer salutes itself like a total narcissist
  code/modules/mob/living/simple_animal/bot/bot.dm
Labels: bugfix

#146 [MIRROR] Updates cryostasis beaker's sprite
  icons/obj/medical/chemical.dmi
Labels: Image

#147 [MIRROR] Ragnarok deathmatch arena now has noteleport area
  _maps/deathmatch/ragnarok.dmm
Labels: bugfix

#160 [MIRROR] Unarmed attacks with carp jaws now uses the bite attack effect
  code/game/machinery/dna_infuser/organ_sets/carp_organs.dm
Labels: Quality of life

#159 [MIRROR] Radioactive nebula no longer runtimes on Runtime station
  code/datums/station_traits/negative_traits.dm
Labels: bugfix

#158 [MIRROR] Fixes black fences and layering issues
  code/game/objects/structures/railings.dm
Labels: bugfix

#157 [MIRROR] Fixes kudzu being able to spawn on openspace turfs resulting in it getting stuck
  code/modules/events/space_vines/vine_event.dm
Labels: bugfix

#155 [MIRROR] Add big manipulator.
  code/datums/greyscale/config_types/greyscale_configs/greyscale_effects.dm
  code/datums/greyscale/config_types/greyscale_configs/greyscale_objects.dm
  code/datums/greyscale/json_configs/big_manipulator.json
  code/datums/greyscale/json_configs/manipulator_hand.json
  code/game/machinery/big_manipulator.dm
  code/game/objects/items/circuitboards/machines/machine_circuitboards.dm
  code/modules/research/designs/machine_designs.dm
  code/modules/research/techweb/nodes/engi_nodes.dm
  icons/obj/machines/big_manipulator.dmi
  icons/obj/machines/big_manipulator_parts/big_manipulator_core.dmi
  icons/obj/machines/big_manipulator_parts/big_manipulator_hand.dmi
  tgstation.dme
  tgui/packages/tgui/interfaces/BigManipulator.tsx
Labels: Feature

#164 [MIRROR] Adjust Vortex Core Max and Beam Rifle recipe.
  code/__DEFINES/research/anomalies.dm
  code/datums/components/crafting/ranged_weapon.dm
Labels: Balance

#165 [MIRROR] reticence require progression
  code/modules/uplink/uplink_items/job.dm
Labels: Balance

#163 [MIRROR] Canonise passive carp
  code/__DEFINES/ai/ai_blackboard.dm
  code/datums/ai/basic_mobs/basic_subtrees/simple_find_nearest_target_to_flee.dm
  code/datums/ai/basic_mobs/basic_subtrees/simple_find_target.dm
  code/datums/ai/basic_mobs/targeting_strategies/basic_targeting_strategy.dm
  code/modules/mob/living/basic/space_fauna/carp/carp.dm
  code/modules/mob/living/basic/space_fauna/carp/carp_ai_rift_actions.dm
  code/modules/mob/living/basic/space_fauna/carp/carp_controllers.dm
  code/modules/mob/living/basic/vermin/crab.dm
  icons/mob/simple/carp.dmi
Labels: Balance, bugfix

#166 [MIRROR] ERTs can now be summoned as a set species
  code/datums/ert.dm
  code/modules/admin/verbs/ert.dm
Labels: Administration

#167 [MIRROR] Windows broken by a Voidwalker now play a cool sound as they reform
  code/game/objects/structures/window.dm
  sound/attributions.txt
  sound/effects/glass_reverse.ogg
Labels: Sound

#101 [MIRROR] Makes the Start Screen Look Better
  _maps/map_files/generic/CentCom.dmm
  code/game/turfs/closed/indestructible.dm
Labels: Server, bugfix

#169 [MIRROR] Fishing toolboxes (and maint) now come with a paper slip containing fishing-related tips.
  code/_globalvars/lists/flavor_misc.dm
  code/_globalvars/lists/maintenance_loot.dm
  code/modules/cargo/goodies.dm
  code/modules/fishing/fishing_equipment.dm
  strings/fishing_tips.txt
Labels: Feature, MIRROR

#170 [MIRROR] [NO GBP] Fixing Clarke's ore box the proper way
  code/modules/mining/boulder_processing/boulder.dm
  code/modules/vehicles/mecha/working/clarke.dm
Labels: MIRROR

#172 [MIRROR] Jarvis, add buckshot to the blackmarket.
  code/game/objects/items/storage/boxes/security_boxes.dm
  code/modules/cargo/markets/market_items/weapons.dm
  code/modules/projectiles/ammunition/_ammunition.dm
  code/modules/projectiles/ammunition/_firing.dm
  code/modules/projectiles/ammunition/ballistic/shotgun.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  code/modules/projectiles/projectile/bullets/shotgun.dm
Labels: Balance, Feature, MIRROR

#161 [MIRROR] Installs bot pathing/delivery nodes on Runtimestation
  _maps/map_files/debug/runtimestation.dmm
Labels: Quality of life

#149 [MIRROR] Icemoon cliffside bench area adjustments (very small)
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
Labels: bugfix

#178 [MIRROR] Reintroduces custom pies and cakes
  code/game/objects/items/food/cake.dm
  code/game/objects/items/food/pie.dm
  icons/obj/food/piecake.dmi
Labels: bugfix, MIRROR

#141 [MIRROR] Fishing expansion 2: one-year later boogaloo
  code/__DEFINES/dcs/signals/signals_fish.dm
  code/__DEFINES/dcs/signals/signals_food.dm
  code/__DEFINES/dcs/signals/signals_reagent.dm
  code/__DEFINES/fish.dm
  code/__DEFINES/traits/declarations.dm
  code/_globalvars/traits/_traits.dm
  code/_globalvars/traits/admin_tooling.dm
  code/controllers/subsystem/processing/fishing.dm
  code/datums/components/bakeable.dm
  code/datums/components/crafting/crafting.dm
  code/datums/components/food/edible.dm
  code/datums/elements/food/grilled_item.dm
  code/datums/elements/food/microwavable.dm
  code/datums/elements/quality_food_ingredient.dm
  code/game/objects/items/food/meatdish.dm
  code/game/turfs/open/ice.dm
  code/game/turfs/open/sand.dm
  code/game/turfs/open/water.dm
  code/modules/fishing/aquarium/aquarium.dm
  code/modules/fishing/aquarium/aquarium_kit.dm
  code/modules/fishing/bait.dm
  code/modules/fishing/fish/_fish.dm
  code/modules/fishing/fish/fish_evolution.dm
  code/modules/fishing/fish/fish_traits.dm
  code/modules/fishing/fish/fish_types.dm
  code/modules/fishing/fish_movement.dm
  code/modules/fishing/fishing_minigame.dm
  code/modules/fishing/fishing_rod.dm
  code/modules/fishing/sources/_fish_source.dm
  code/modules/fishing/sources/source_types.dm
  code/modules/mapfluff/ruins/icemoonruin_code/hotsprings.dm
  code/modules/power/cell.dm
  code/modules/unit_tests/fish_unit_tests.dm
  icons/hud/fishing_hud.dmi
  icons/mob/inhands/fish_lefthand.dmi
  icons/mob/inhands/fish_righthand.dmi
  icons/obj/aquarium/fish.dmi
  icons/obj/aquarium/wide.dmi
  icons/obj/food/meat.dmi
  icons/turf/overlays.dmi
  tgstation.dme
Labels: Balance, Feature

#176 [MIRROR] Updates goliath cloak sprites
  icons/mob/clothing/head/helmet.dmi
  icons/mob/clothing/suits/armor.dmi
  icons/obj/clothing/suits/armor.dmi
Labels: Image, MIRROR

#168 [MIRROR] Adds a botany area to the Syndicate Lavaland base
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
  code/game/area/areas/ruins/lavaland.dm
Labels: Feature

#171 [MIRROR] Clicking floor tiles now also closes curator/morgue doors
  code/game/machinery/doors/door.dm
Labels: Quality of life, MIRROR

#177 [MIRROR] Adds Punching Mitts: Become a One-Spacemen Planetary Ecological Disaster. Available in any mining loot chests (and portals)
  code/__DEFINES/melee.dm
  code/datums/martial/boxing.dm
  code/game/objects/structures/icemoon/cave_entrance.dm
  code/modules/clothing/gloves/punch_mitts.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mob/living/basic/lavaland/legion/legion.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/_megafauna.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/blood_drunk_miner.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/demonic_frost_miner.dm
  icons/mob/clothing/hands.dmi
  icons/obj/clothing/gloves.dmi
  tgstation.dme
Labels: Balance, Feature, MIRROR

#173 Pun Pun is now playable as a station job trait
  icons/mob/huds/hud.dmi
  tgstation.dme
  tgui/packages/tgui/interfaces/common/JobToIcon.ts
  wallstation_modules/station_traits/code/pun_pun.dm
  wallstation_modules/station_traits/icons/id_trim.dmi
  wallstation_modules/station_traits/icons/monkey_shotgun.dmi
  wallstation_modules/station_traits/icons/signup_button.dmi
Labels: Feature

#182 [MIRROR] Goliath arm can now defuse gibonite
  code/game/turfs/closed/minerals.dm
Labels: Quality of life, MIRROR

#180 [MIRROR] Adds descriptions to aquarium decoration items
  code/modules/fishing/aquarium/aquarium_kit.dm
Labels: Grammer, bugfix, MIRROR

#179 [MIRROR] [NO GBP] Partially reverts a change to *Rusted Ritual*
  code/modules/antagonists/heretic/knowledge/side_rust_cosmos.dm
Labels: Balance, MIRROR

#181 [MIRROR] Marine helmets no longer change their sprite to security helmets when their flashlight is toggled
  code/modules/clothing/head/helmet.dm
Labels: bugfix, MIRROR

#130 [MIRROR] Adds three new deathmatch maps - Ragnarok, Lattice Battles, Species Showdown
  _maps/deathmatch/lattice_battles.dmm
  _maps/deathmatch/ragnarok.dmm
  _maps/deathmatch/species_warfare.dmm
  code/__DEFINES/antagonists.dm
  code/__DEFINES/inventory.dm
  code/__DEFINES/traits/declarations.dm
  code/__HELPERS/mobs.dm
  code/_globalvars/traits/_traits.dm
  code/_globalvars/traits/admin_tooling.dm
  code/datums/outfit.dm
  code/game/atom/atom_act.dm
  code/game/objects/effects/spawners/random/decoration.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/granters/magic/lightning_bolt.dm
  code/game/objects/structures/railings.dm
  code/game/turfs/closed/wall/misc_walls.dm
  code/game/turfs/open/floor/misc_floor.dm
  code/modules/antagonists/cult/blood_magic.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/antagonists/cult/datums/cult_team.dm
  code/modules/antagonists/cult/datums/cultist.dm
  code/modules/antagonists/cult/runes.dm
  code/modules/antagonists/heretic/heretic_knowledge.dm
  code/modules/antagonists/heretic/heretic_living_heart.dm
  code/modules/antagonists/heretic/influences.dm
  code/modules/antagonists/heretic/items/forbidden_book.dm
  code/modules/antagonists/heretic/items/heretic_blades.dm
  code/modules/antagonists/heretic/knowledge/flesh_lore.dm
  code/modules/antagonists/heretic/knowledge/general_side.dm
  code/modules/antagonists/heretic/knowledge/lock_lore.dm
  code/modules/antagonists/heretic/knowledge/rust_lore.dm
  code/modules/antagonists/heretic/knowledge/sacrifice_knowledge/sacrifice_knowledge.dm
  code/modules/antagonists/heretic/knowledge/starting_lore.dm
  code/modules/antagonists/heretic/transmutation_rune.dm
  code/modules/antagonists/wizard/equipment/soulstone.dm
  code/modules/clothing/shoes/cult.dm
  code/modules/clothing/suits/costume.dm
  code/modules/deathmatch/deathmatch_loadouts.dm
  code/modules/deathmatch/deathmatch_mapping.dm
  code/modules/deathmatch/deathmatch_maps.dm
  code/modules/jobs/job_types/chaplain/chaplain_nullrod.dm
  code/modules/mob/living/carbon/human/_species.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/unit_tests/outfit_sanity.dm
  icons/mob/clothing/belt.dmi
  icons/mob/clothing/belt_mirror.dmi
  tgstation.dme
  wallstation_modules/deathmatch_fix/code/deathmatch_maps.dm
  wallstation_modules/deathmatch_fix/code/misc_walls.dm
Labels: Feature, MIRROR

#119 [MIRROR] Adds taunting as a replacement for spin/flip in style meter and parrying
  code/__DEFINES/mobs.dm
  code/__DEFINES/traits/declarations.dm
  code/__DEFINES/traits/sources.dm
  code/_globalvars/traits/_traits.dm
  code/_globalvars/traits/admin_tooling.dm
  code/datums/components/style/style.dm
  code/modules/bitrunning/orders/tech.dm
  code/modules/library/skill_learning/generic_skillchips/matrix_flip.dm
  code/modules/mob/emote.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/living/living.dm
  code/modules/projectiles/projectile.dm
  icons/mob/effects/blocking.dmi
Labels: Balance, Feature, MIRROR

#183 [MIRROR] Hierophant no longer lies about obliterating someone
  code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
Labels: Grammer, MIRROR

#111 [MIRROR] Special radio channels now use bitflags instead of individual vars
  _maps/RandomRuins/IceRuins/icemoon_underground_comms_agent.dmm
  _maps/map_files/generic/CentCom.dmm
  code/__DEFINES/radio.dm
  code/game/machinery/telecomms/broadcasting.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/devices/radio/intercom.dm
  code/game/objects/items/devices/radio/radio.dm
  code/modules/admin/verbs/borgpanel.dm
  code/modules/capture_the_flag/ctf_classes.dm
  code/modules/mob/living/carbon/human/human_say.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/pai/say.dm
  code/modules/unit_tests/say.dm
  code/modules/vehicles/mecha/equipment/tools/radio.dm
Labels: Code improvement, MIRROR

#185 [MIRROR] Fix grammar error on Hilbert
  code/modules/mapfluff/ruins/spaceruin_code/hilbertshotel.dm
Labels: Grammer, MIRROR

#186 [MIRROR] Athletic Fishing Gloves and Fishing Module to fish without a fishing rod
  code/__DEFINES/traits/declarations.dm
  code/_globalvars/traits/_traits.dm
  code/datums/components/profound_fisher.dm
  code/game/machinery/newscaster/newscaster_machine.dm
  code/modules/clothing/gloves/special.dm
  code/modules/fishing/fishing_minigame.dm
  code/modules/fishing/fishing_rod.dm
  code/modules/mod/modules/modules_general.dm
  code/modules/modular_computers/computers/item/pda.dm
  code/modules/modular_computers/file_system/programs/messenger/messenger_program.dm
  code/modules/research/designs/mechfabricator_designs.dm
  code/modules/research/designs/misc_designs.dm
  code/modules/research/techweb/nodes/service_nodes.dm
  code/modules/tgui/states/reverse_contained.dm
  icons/mob/clothing/hands.dmi
  icons/mob/clothing/modsuit/mod_modules.dmi
  icons/mob/inhands/clothing/gloves_lefthand.dmi
  icons/mob/inhands/clothing/gloves_righthand.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/modsuit/mod_modules.dmi
  tgstation.dme
Labels: Feature, MIRROR

#187 [MIRROR] Add messages (paper, photos, cash) in bottles.
  _maps/RandomRuins/LavaRuins/lavaland_biodome_beach.dmm
  _maps/RandomZLevels/TheBeach.dmm
  code/__DEFINES/database.dm
  code/__DEFINES/fish.dm
  code/__DEFINES/paper.dm
  code/__DEFINES/traits/declarations.dm
  code/_globalvars/traits/_traits.dm
  code/controllers/subsystem/persistence/_persistence.dm
  code/controllers/subsystem/persistence/message_bottles.dm
  code/datums/components/fishing_spot.dm
  code/datums/json_database.dm
  code/game/objects/effects/spawners/message_in_a_bottle.dm
  code/game/objects/items/food/misc.dm
  code/game/turfs/open/sand.dm
  code/game/turfs/open/water.dm
  code/modules/cargo/order.dm
  code/modules/cargo/orderconsole.dm
  code/modules/fishing/fishing_minigame.dm
  code/modules/fishing/sources/_fish_source.dm
  code/modules/fishing/sources/source_types.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_drink.dm
  code/modules/paperwork/paper.dm
  code/modules/photography/photos/photo.dm
  code/modules/reagents/reagent_containers/cups/glassbottle.dm
  icons/effects/random_spawners.dmi
  icons/hud/fishing_hud.dmi
  icons/obj/drinks/bottles.dmi
  tgstation.dme
Labels: Feature, MIRROR

#189 [MIRROR] Deletes teleport subtype of deathmatch area, removes consoles and gascanisters from species deathmatch. Changes some loadouts.
  _maps/deathmatch/ragin_mages.dmm
  _maps/deathmatch/species_warfare.dmm
  code/modules/deathmatch/deathmatch_loadouts.dm
  code/modules/deathmatch/deathmatch_mapping.dm
Labels: Server, Removal, bugfix, MIRROR

#190 [MIRROR] Fixing three fishing issues in one PR.
  code/datums/components/chasm.dm
  code/modules/fishing/fish/chasm_detritus.dm
  code/modules/fishing/fishing_rod.dm
  code/modules/mob_spawn/mob_spawn.dm
Labels: bugfix, MIRROR

#191 [MIRROR] 500 cigarettes, and one edible component update
  code/__DEFINES/achievements.dm
  code/datums/achievements/misc_achievements.dm
  code/datums/components/food/edible.dm
  code/game/objects/items/cigs_lighters.dm
  icons/ui/achievements/achievements.dmi
Labels: Code improvement, Balance, Feature, MIRROR
